spring:
  application:
    name: saudacao-service

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"

saudacao-service:
  saudacao: "Ola (HOM)"
  default-value: "Mundo (HOM)"

